labels:
  feature: "Feature"
  needs_rebase: "Needs Rebase"
  lts: "LTS Backport"
  rendering: "Rendering"
  assigned: "Assigned"
  new_event: "New Event"
  triage: "Triage"
  latest: "1.19"
labelLocks:
  Forum:
    lock: true
    lockReason: null
    close: true
    message: |-
      :wave: We use the issue tracker exclusively for final bug reports and feature requests.
      However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/) or [Forge Discord](https://discord.minecraftforge.net/).
      Please create a new topic on the support forum with this issue or ask in the `#tech-support` channel in the Discord server, and the conversation can continue there.
  Spam:
    lock: true
    lockReason: "spam"
    close: true
    message: null
triage:
  teamName: "triage"
  projectId: 4
labelTeams:
  default:
  - "TheCurle"
  - "LexManos"
  Rendering: "rendering"
  LTS Backport: "legacy"
commands:
  prefixes:
  - "/"
  - "@autoforge "
  allowEdits: false
  minimizeComment: true
  reactToComment: true
